name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.9'  # Use the latest stable Julia version

      - name: Install dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'

      - name: Run Tests
        run: julia --project=@. -e 'using Pkg; Pkg.test()'
